create_folders <- function(outfolder_location){
  dir.create(outfolder_location, showWarnings = FALSE)
  dir.create(paste(outfolder_location,'signatures/',sep=""), showWarnings = FALSE)
  dir.create(paste(outfolder_location,'signatures/go_terms/',sep=""), showWarnings = FALSE)
  dir.create(paste(outfolder_location,'signatures/go_terms_IEA_filtered/',sep=""), showWarnings = FALSE)
  dir.create(paste(outfolder_location,'signatures/affy_ids/',sep=""), showWarnings = FALSE)
  dir.create(paste(outfolder_location,'connectivity_map/',sep=""), showWarnings = FALSE)
  dir.create(paste(outfolder_location,'connectivity_map/by_ATC/',sep=""), showWarnings = FALSE)
  dir.create(paste(outfolder_location,'connectivity_map/by_name',sep=""), showWarnings = FALSE)
  dir.create(paste(outfolder_location,'connectivity_map/by_celltype',sep=""), showWarnings = FALSE)
  dir.create(paste(outfolder_location,'connectivity_map/scores/',sep=""), showWarnings = FALSE)
  dir.create(paste(outfolder_location,'connectivity_map/up_vs_down/',sep=""), showWarnings = FALSE)
  dir.create(paste(outfolder_location,'connectivity_map/detailed_results/',sep=""), showWarnings = FALSE)
  dir.create(paste(outfolder_location,'connectivity_map/permuted_results/',sep=""), showWarnings = FALSE)
  dir.create(paste(outfolder_location,'candidate_drugs/',sep=""), showWarnings = FALSE)
  dir.create(paste(outfolder_location,'candidate_drugs/',sep=""), showWarnings = FALSE)
  dir.create(paste(outfolder_location,'candidate_drugs/by_name/',sep=""), showWarnings = FALSE)
  dir.create(paste(outfolder_location,'candidate_drugs/by_celltype/',sep=""), showWarnings = FALSE)
  dir.create(paste(outfolder_location,'candidate_drugs/by_ATC/',sep=""), showWarnings = FALSE)
  dir.create(paste(outfolder_location,'webpage_results/',sep=""), showWarnings = FALSE)
}